### ISSUE TITLE
Unable to ask follow up question using the chat webview

### ISSUE THREAD

**Issue by olasunkanmi-SE** [olasunkanmi-SE/codebuddy#37]
# Current Behavior
When interacting with the webview to ask questions, the view.webview.onDidReceiveMessage event is triggered for the initial question, allowing the message to be successfully sent to the LLM and subsequently displayed in the webview. However, for subsequent questions, the view.webview.onDidReceiveMessage event fails to fire, preventing the message from being sent to the LLM and subsequently the webview.
# Expected Behavior
The webview thread should always be updated.

**Comment by zahir535** [comment]
Please let em work on this issue @olasunkanmi-SE

**Comment by olasunkanmi-SE** [comment]
`private setupMessageHandler(
    apiKey: string,
    modelName: string,
    _view: vscode.WebviewView,
  ): void {
    try {
          _view.webview.onDidReceiveMessage(async (message) => {
      if (message.type === "user-input") {
        const response = await this.generateResponse(
          apiKey,
          modelName,
          formatText(message.message),
        );
        if (response) {
          this.sendResponse(formatText(response), "bot");
        }
      }
    });
    } catch (error) {
      console.error(error)
    }
  }`
onDidReceiveMessage call back isn't called on the second and subsequent user prompts. The onDidReceiveMessage method is called because we can see the user prompts on the chat view, but it doesn't call the callback function. And there is no error logged

**Comment by olasunkanmi-SE** [comment]
PR: https://github.com/olasunkanmi-SE/codebuddy/pull/109
