### ISSUE TITLE
Seperate the view into individual modules

### ISSUE THREAD

**Issue by olasunkanmi-SE** [olasunkanmi-SE/codebuddy#38]
Currently the webview contains HTML, CSS and JS in one file. These files need to be separated to individual files

**Comment by mVedr** [comment]
Hi I would like to work on this issue ....Is this repo open for contributions?

**Comment by olasunkanmi-SE** [comment]
Yes, it is and your PR has been merged. Thanks for contributing. Please feel free to work on other issues that excites you.

**Comment by olasunkanmi-SE** [comment]
PR: https://github.com/olasunkanmi-SE/codebuddy/pull/43
