### ISSUE TITLE
Markdown improvement

### ISSUE THREAD

**Issue by olasunkanmi-SE** [olasunkanmi-SE/codebuddy#47]
Currently the chat interface looks like this. But we want to achieve the image below this one
<img width="660" alt="Screenshot 2024-05-09 at 10 36 39 AM" src="https://github.com/olasunkanmi-SE/codebuddy/assets/60177090/d8acd56c-a424-4d46-8238-6a8b6fa18e60">

We want this instead
<img width="779" alt="Screenshot 2024-05-09 at 10 41 51 AM" src="https://github.com/olasunkanmi-SE/codebuddy/assets/60177090/4d99f950-aef3-45aa-9dc5-c36f741e9f87">

This application uses the markdown-it npm package to render the chat interface.

**Comment by darkelfs56** [comment]
Hi Ola, you can assign that to me. 👍

**Comment by olasunkanmi-SE** [comment]
PR: https://github.com/olasunkanmi-SE/codebuddy/pull/52
