### ISSUE TITLE
 copy button within the chat webview to copy the code

### ISSUE THREAD

**Issue by olasunkanmi-SE** [olasunkanmi-SE/codebuddy#48]
Behavior
Application does not provide a means to copy the rendered code from the webview

<img width="660" alt="Screenshot 2024-05-09 at 10 36 39 AM" src="https://github.com/olasunkanmi-SE/codebuddy/assets/60177090/08853899-dbca-454e-a04f-3d15375d288e">

Expected Bahavior
There should be a copy button within the chat webview to copy the code
Attach the copy button to the rendered code
<img width="779" alt="Screenshot 2024-05-09 at 10 41 51 AM" src="https://github.com/olasunkanmi-SE/codebuddy/assets/60177090/717dfa5d-7e09-40ea-abc8-4603a01d3fa6">

**Comment by fakhrul-haziq** [comment]
Hi @olasunkanmi-SE, I'm going to start working on this one

**Comment by fakhrul-haziq** [comment]
Hi @olasunkanmi-SE , I would like to working on this one

**Comment by FakhrulZiq** [comment]
Hi @olasunkanmi-SE, I'm going to start working on this one
