### ISSUE TITLE
Feature Request: Add Scroll Down Button for Better Navigation

### ISSUE THREAD

**Issue by fakhrul-haziq** [olasunkanmi-SE/codebuddy#54]
**Description:**
To enhance the user experience, I propose adding a scroll down button to the interface. This feature will allow users to quickly navigate to the latest content, improving accessibility and ease of use.

**Implementation:**
The scroll down button can be positioned at the bottom of the interface, becoming visible when there is content out of view. Clicking the button will smoothly scroll the user to the latest content.

**Example:**
Here is an example of how it can be implemented, including the visual representation in the UI.

![image](https://github.com/olasunkanmi-SE/codebuddy/assets/143057150/b6b3b9e1-5ad7-4bbd-8bf5-176f51bc6298)

Please let me know if this feature aligns with the project's goals, and I'd be happy to work on it.

Thank you!

**Comment by FakhrulZiq** [comment]
Hi @olasunkanmi-SE I would like to work on this features

**Comment by Jaishree2310** [comment]
Hi @olasunkanmi-SE Can you assign this issue to me? 
Thanks!
