### ISSUE TITLE
Feature Request: Auto commit message.

### ISSUE THREAD

**Issue by eshanregov** [olasunkanmi-SE/codebuddy#60]
To simplify creating commit messages for our staged changes, this feature would be ideal for developers. Using it will help us maintain clear and consistent commit messages in our repository.

**Reference:**
[Codium AI](https://codiumate-docs.codium.ai/chat/commands/commit/)

**Comment by olasunkanmi-SE** [comment]
https://github.com/olasunkanmi-SE/codebuddy/pull/71
